# -*- coding: utf-8 -*-
"""TTS-GPT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_fR44VqCekEZpHrzcOHBgyTzDDJ6sn4I
"""

pip install --upgrade openai

!openai migrate
!pip install openai>=1.0.0
!openai==0.28
!pip install openai

import openai

openai.api_key = "sk-....."

def get_completion(prompt, model="gpt-3.5-turbo"):
    messages = [{"role": "user", "content": prompt}]
    response = openai.ChatCompletion.create(model=model, messages=messages, temperature=0)
    return response.choices[0].message["content"]

while True:
    user_input = input('You: ')
    if user_input.lower() == 'q':
        break
    print('GPT:', get_completion(user_input))